package core_test

import (
	"context"
	"testing"

	"github.com/crom/crom-agente/internal/agents/core"
	"github.com/crom/crom-agente/internal/llm/providers"
)

// MockAgent implementa a interface core.Agent para fins de testes
type MockAgent struct {
	NameVal        string
	DescriptionVal string
	SysPromptVal   string
	ToolIDsVal     []string
	ExecuteResult  core.AgentResult
	ExecuteErr     error
}

func (m *MockAgent) Name() string {
	return m.NameVal
}

func (m *MockAgent) Description() string {
	return m.DescriptionVal
}

func (m *MockAgent) SystemPrompt() string {
	return m.SysPromptVal
}

func (m *MockAgent) ToolIDs() []string {
	return m.ToolIDsVal
}

func (m *MockAgent) Execute(ctx context.Context, prompt string, priorSummary string) (core.AgentResult, error) {
	return m.ExecuteResult, m.ExecuteErr
}

func TestBaseAgent(t *testing.T) {
	// Teste de validação sem provider
	ba := &core.BaseAgent{
		AgentName: "TestAgent",
	}

	if err := ba.Validate(); err == nil {
		t.Errorf("esperava erro de validação por falta de provedor LLM")
	}

	// Teste de validação sem nome
	baNoName := &core.BaseAgent{
		LLMProvider: nil, // Mock ou nil
	}
	if err := baNoName.Validate(); err == nil {
		t.Errorf("esperava erro de validação por falta de nome")
	}
}

func TestMockAgentInterface(t *testing.T) {
	var _ core.Agent = &MockAgent{}

	ma := &MockAgent{
		NameVal:        "mock-specialist",
		DescriptionVal: "Mock specialist description",
		SysPromptVal:   "You are a mock specialist",
		ExecuteResult: core.AgentResult{
			Output:         "Mock output",
			ContextSummary: "Mock summary",
		},
	}

	if ma.Name() != "mock-specialist" {
		t.Errorf("Name() incorreto: %s", ma.Name())
	}

	if ma.Description() != "Mock specialist description" {
		t.Errorf("Description() incorreto: %s", ma.Description())
	}

	if ma.SystemPrompt() != "You are a mock specialist" {
		t.Errorf("SystemPrompt() incorreto: %s", ma.SystemPrompt())
	}

	res, err := ma.Execute(context.Background(), "do something", "")
	if err != nil {
		t.Fatalf("Execute falhou inesperadamente: %v", err)
	}

	if res.Output != "Mock output" {
		t.Errorf("res.Output incorreto: %s", res.Output)
	}

	if res.ContextSummary != "Mock summary" {
		t.Errorf("res.ContextSummary incorreto: %s", res.ContextSummary)
	}
}

func TestCompressHistory(t *testing.T) {
	// Teste do fallback com provider nil
	fallbackRes, err := core.CompressHistory(context.Background(), nil, "write a file", "success", "previous work done")
	if err != nil {
		t.Fatalf("CompressHistory (nil provider) falhou: %v", err)
	}
	if fallbackRes == "" {
		t.Errorf("esperava resumo fallback preenchido")
	}

	// Teste com provider mock
	mock := providers.NewMockProvider(providers.MockTextResponse("Summary content generated by AI", 10))
	res, err := core.CompressHistory(context.Background(), mock, "write a file", "success", "previous work done")
	if err != nil {
		t.Fatalf("CompressHistory (mock provider) falhou: %v", err)
	}
	if res != "Summary content generated by AI" {
		t.Errorf("esperava 'Summary content generated by AI', obteve '%s'", res)
	}
}

